// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as BoolKVServiceJs from "./BoolKVService.js";
import * as Helpers from "@skipruntime/helpers";

let service = BoolKVServiceJs.service;

let defaultOpts = {
  streaming_port: 18093,
  control_port: 18092,
  platform: "wasm",
  no_cors: undefined
};

function start(opts) {
  return SkipruntimeServer.Natural.runService(service, opts);
}

function stop(server) {
  return SkipruntimeServer.Natural.close(server);
}

let Server = {
  service: service,
  defaultOpts: defaultOpts,
  start: start,
  stop: stop
};

let localhost = "127.0.0.1";

function makeBroker(opts) {
  return new Helpers.SkipServiceBroker({
    host: localhost,
    streaming_port: opts.streaming_port,
    control_port: opts.control_port,
    secured: undefined
  }, undefined);
}

let Client = {
  localhost: localhost,
  makeBroker: makeBroker
};

function logBoolKV(entries) {
  let rows = entries.map(param => {
    let vals = param[1];
    let k = param[0];
    if (vals.length !== 1) {
      return [
        "<unexpected>",
        typeof k,
        "<unexpected>",
        typeof k
      ];
    }
    let v = vals[0];
    return [
      JSON.stringify(k),
      typeof k,
      JSON.stringify(v),
      typeof v
    ];
  });
  console.log("boolKV snapshot", rows);
}

async function run() {
  console.log("bool-kv: starting BoolKVService on 18092/18093…");
  let server = await start(defaultOpts);
  console.log("bool-kv: service started");
  let broker = makeBroker(defaultOpts);
  let entries = await broker.getAll("boolKV", null);
  logBoolKV(entries);
  await SkipruntimeServer.Natural.close(server);
  console.log("bool-kv: service closed");
}

run();

export {
  Server,
  Client,
  logBoolKV,
  run,
}
/* service Not a pure module */
