// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";
import * as SkipruntimeFixpoint from "../bindings/SkipruntimeFixpoint.res.js";

function makeDCEService(nodes, roots, edges) {
  let fixpoint = SkipruntimeFixpoint.make(roots);
  edges.forEach(param => {
    let from = param[0];
    param[1].forEach(to_ => {
      SkipruntimeFixpoint.addToStep(fixpoint, from, to_);
    });
  });
  return {
    nodes: nodes,
    fixpoint: fixpoint
  };
}

function getLiveSet(service) {
  return SkipruntimeFixpoint.current(service.fixpoint);
}

function getDeadSet(service) {
  let live = new Set(SkipruntimeFixpoint.current(service.fixpoint));
  return service.nodes.filter(node => !live.has(node));
}

function addRoot(service, root) {
  return SkipruntimeFixpoint.addToBase(service.fixpoint, root);
}

function removeRoot(service, root) {
  return SkipruntimeFixpoint.removeFromBase(service.fixpoint, root);
}

function addEdge(service, from, to_) {
  return SkipruntimeFixpoint.addToStep(service.fixpoint, from, to_);
}

function removeEdge(service, from, to_) {
  return SkipruntimeFixpoint.removeFromStep(service.fixpoint, from, to_);
}

function log(prim) {
  console.log(prim);
}

function logArray(label, arr) {
  console.log(label + ": [" + arr.toSorted(Primitive_string.compare).join(", ") + "]");
}

function demo() {
  console.log("Dead Code Elimination Demo");
  console.log("==========================");
  console.log("");
  let service = makeDCEService([
    "main",
    "utils",
    "helpers",
    "api",
    "db",
    "logger",
    "unused1",
    "unused2"
  ], ["main"], [
    [
      "main",
      [
        "utils",
        "api"
      ]
    ],
    [
      "utils",
      ["helpers"]
    ],
    [
      "api",
      [
        "db",
        "logger"
      ]
    ],
    [
      "unused1",
      ["unused2"]
    ]
  ]);
  console.log("Initial graph:");
  console.log("  main → utils, api");
  console.log("  utils → helpers");
  console.log("  api → db, logger");
  console.log("  unused1 → unused2");
  console.log("");
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  logArray("Dead set", getDeadSet(service));
  console.log("");
  console.log("--- Add 'unused1' as a new root ---");
  let changes1 = SkipruntimeFixpoint.addToBase(service.fixpoint, "unused1");
  logArray("Added", changes1.added);
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  logArray("Dead set", getDeadSet(service));
  console.log("");
  console.log("--- Remove 'main' root ---");
  let changes2 = SkipruntimeFixpoint.removeFromBase(service.fixpoint, "main");
  logArray("Removed", changes2.removed);
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  logArray("Dead set", getDeadSet(service));
  console.log("");
  console.log("--- Add 'main' root back ---");
  let changes3 = SkipruntimeFixpoint.addToBase(service.fixpoint, "main");
  logArray("Added", changes3.added);
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  console.log("");
  console.log("--- Remove edge main → api ---");
  let changes4 = removeEdge(service, "main", "api");
  logArray("Removed", changes4.removed);
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  console.log("");
  console.log("--- Add edge helpers → main (creates cycle) ---");
  addEdge(service, "helpers", "main");
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  console.log("");
  console.log("--- Remove edge main → utils ---");
  console.log("    (helpers → main cycle should die because no wf-deriver)");
  let changes6 = removeEdge(service, "main", "utils");
  logArray("Removed", changes6.removed);
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  console.log("");
  console.log("Demo complete!");
}

function alternativePathDemo() {
  console.log("");
  console.log("Alternative Path Demo");
  console.log("=====================");
  console.log("(This tests the edge case that required algorithm revision)");
  console.log("");
  let service = makeDCEService([
    "main",
    "api",
    "backup",
    "db"
  ], ["main"], [
    [
      "main",
      [
        "api",
        "backup"
      ]
    ],
    [
      "api",
      ["db"]
    ],
    [
      "backup",
      ["db"]
    ]
  ]);
  console.log("Graph with redundant paths to db:");
  console.log("  main → api → db");
  console.log("  main → backup → db");
  console.log("");
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  logArray("Dead set", getDeadSet(service));
  console.log("");
  console.log("--- Remove edge main → api ---");
  console.log("    (db should survive via backup path)");
  let changes = removeEdge(service, "main", "api");
  logArray("Removed", changes.removed);
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  console.log("");
  let dbIsLive = SkipruntimeFixpoint.current(service.fixpoint).includes("db");
  if (dbIsLive) {
    console.log("✓ CORRECT: db survived via alternative path (main → backup → db)");
  } else {
    console.log("✗ BUG: db was incorrectly removed!");
  }
  console.log("");
  console.log("--- Remove edge backup → db ---");
  console.log("    (now db has no path from main)");
  let changes2 = removeEdge(service, "backup", "db");
  logArray("Removed", changes2.removed);
  logArray("Live set", SkipruntimeFixpoint.current(service.fixpoint));
  console.log("");
  console.log("Alternative path demo complete!");
}

demo();

alternativePathDemo();

export {
  makeDCEService,
  getLiveSet,
  getDeadSet,
  addRoot,
  removeRoot,
  addEdge,
  removeEdge,
  log,
  logArray,
  demo,
  alternativePathDemo,
}
/*  Not a pure module */
