// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as SkipruntimeCore from "../bindings/SkipruntimeCore.res.js";

let status = SkipruntimeCore.LoadStatus.fromJs(2);

console.log("status", status);

let ex = SkipruntimeCore.Errors.nonUniqueValue("boom");

console.log("error message", Stdlib_JsExn.message(ex));

let back = SkipruntimeCore.LoadStatus.toJs("incompatible");

console.log("status back to js", back);

let mapperClass = SkipruntimeCore.Natural.Mapper.make((_key, _values, _ctx, _params) => [[
    "k",
    null
  ]]);

console.log("mapper class", mapperClass);

let doubledMapper = SkipruntimeCore.Natural.Mapper.make((key, values, _ctx, _params) => Belt_Array.map(values.toArray(), v => {
  if (typeof v === "number") {
    return [
      key,
      v * 2
    ];
  } else {
    return [
      key,
      v
    ];
  }
}));

let sumReducer = SkipruntimeCore.Natural.Reducer.make(_params => (0), (acc, value, _params) => {
  if (typeof acc === "number" && typeof value === "number") {
    return acc + value;
  } else {
    return acc;
  }
}, undefined);

console.log("doubled mapper", doubledMapper);

console.log("sum reducer", sumReducer);

/* status Not a pure module */
