// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fixpoint from "../bindings/Fixpoint.res.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Belt_MapString from "@rescript/runtime/lib/es6/Belt_MapString.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_string from "@rescript/runtime/lib/es6/Primitive_string.js";

function log(msg) {
  console.log(msg);
}

function logArray(label, arr) {
  console.log(label + ": [" + arr.join(", ") + "]");
}

let passed = {
  contents: 0
};

let failed = {
  contents: 0
};

let failures = {
  contents: []
};

function assertEqual(actual, expected, msg) {
  if (Primitive_object.equal(actual, expected)) {
    console.log("✓ " + msg);
    passed.contents = passed.contents + 1 | 0;
  } else {
    console.log("✗ " + msg);
    console.log("  Expected: " + Stdlib_Option.getOr(JSON.stringify(expected), "?"));
    console.log("  Actual: " + Stdlib_Option.getOr(JSON.stringify(actual), "?"));
    failed.contents = failed.contents + 1 | 0;
    failures.contents = failures.contents.concat([msg]);
  }
}

function assertArrayEqual(actual, expected, msg) {
  let sortedActual = actual.toSorted(Primitive_string.compare);
  let sortedExpected = expected.toSorted(Primitive_string.compare);
  assertEqual(sortedActual, sortedExpected, msg);
}

function printSummary() {
  let total = passed.contents + failed.contents | 0;
  let msg = "\n" + "=".repeat(60);
  console.log(msg);
  console.log("TEST SUMMARY");
  let msg$1 = "=".repeat(60);
  console.log(msg$1);
  let msg$2 = `Total:  ` + total.toString() + ` tests`;
  console.log(msg$2);
  let msg$3 = `Passed: ` + passed.contents.toString() + ` ✓`;
  console.log(msg$3);
  let msg$4 = `Failed: ` + failed.contents.toString() + ` ✗`;
  console.log(msg$4);
  if (failed.contents > 0) {
    console.log("\nFailed tests:");
    failures.contents.forEach(f => {
      console.log("  - " + f);
    });
  }
  let msg$5 = "=".repeat(60);
  console.log(msg$5);
  if (failed.contents === 0) {
    console.log("All tests passed! 🎉");
    return;
  }
  let msg$6 = failed.contents.toString() + ` test(s) failed.`;
  console.log(msg$6);
}

function testInitialGraph() {
  console.log("\n=== Test: Initial Graph ===");
  let edges = Belt_MapString.fromArray([
    [
      "R",
      ["A"]
    ],
    [
      "A",
      [
        "B",
        "D"
      ]
    ],
    [
      "B",
      ["C"]
    ],
    [
      "D",
      ["B"]
    ]
  ]);
  let config = {
    stepFwd: x => Belt_MapString.getWithDefault(edges, x, [])
  };
  let state = Fixpoint.make(config, ["R"]);
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B",
    "C",
    "D"
  ], "Initial fixpoint contains R, A, B, C, D");
  assertEqual(Fixpoint.rank(state, "R"), 0, "R has rank 0");
  assertEqual(Fixpoint.rank(state, "A"), 1, "A has rank 1");
  assertEqual(Fixpoint.rank(state, "B"), 2, "B has rank 2");
  assertEqual(Fixpoint.rank(state, "C"), 3, "C has rank 3");
  assertEqual(Fixpoint.rank(state, "D"), 2, "D has rank 2");
  return state;
}

function testExpansion() {
  console.log("\n=== Test: Expansion (Add Edge) ===");
  let edges = Belt_MapString.fromArray([
    [
      "R",
      [
        "A",
        "E"
      ]
    ],
    [
      "A",
      [
        "B",
        "D"
      ]
    ],
    [
      "B",
      ["C"]
    ],
    [
      "D",
      ["B"]
    ],
    [
      "E",
      ["F"]
    ]
  ]);
  let config = {
    stepFwd: x => Belt_MapString.getWithDefault(edges, x, [])
  };
  let originalEdges = Belt_MapString.fromArray([
    [
      "R",
      ["A"]
    ],
    [
      "A",
      [
        "B",
        "D"
      ]
    ],
    [
      "B",
      ["C"]
    ],
    [
      "D",
      ["B"]
    ]
  ]);
  let originalConfig = {
    stepFwd: x => Belt_MapString.getWithDefault(originalEdges, x, [])
  };
  let state = Fixpoint.make(originalConfig, ["R"]);
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B",
    "C",
    "D"
  ], "Before expansion: R, A, B, C, D");
  let newState = Fixpoint.make(config, ["R"]);
  assertArrayEqual(Fixpoint.current(newState), [
    "R",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F"
  ], "After expansion: R, A, B, C, D, E, F");
  assertEqual(Fixpoint.rank(newState, "E"), 1, "E has rank 1");
  assertEqual(Fixpoint.rank(newState, "F"), 2, "F has rank 2");
}

function testContraction() {
  console.log("\n=== Test: Contraction (Remove Edge) ===");
  let fullEdges = Belt_MapString.fromArray([
    [
      "R",
      ["A"]
    ],
    [
      "A",
      [
        "B",
        "D"
      ]
    ],
    [
      "B",
      ["C"]
    ],
    [
      "D",
      ["B"]
    ]
  ]);
  let fullConfig = {
    stepFwd: x => Belt_MapString.getWithDefault(fullEdges, x, [])
  };
  let state = Fixpoint.make(fullConfig, ["R"]);
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B",
    "C",
    "D"
  ], "Before contraction: R, A, B, C, D");
  let changes = Fixpoint.applyDelta(state, {
    addedToBase: Fixpoint.emptyDelta.addedToBase,
    removedFromBase: Fixpoint.emptyDelta.removedFromBase,
    addedToStep: Fixpoint.emptyDelta.addedToStep,
    removedFromStep: [[
        "A",
        "D"
      ]]
  });
  logArray("Removed elements", changes.removed);
  assertArrayEqual(changes.removed, ["D"], "D was removed");
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B",
    "C"
  ], "After contraction: R, A, B, C");
}

function testCycleContraction() {
  console.log("\n=== Test: Cycle Contraction ===");
  let edges = Belt_MapString.fromArray([
    [
      "R",
      ["A"]
    ],
    [
      "A",
      ["B"]
    ],
    [
      "B",
      ["A"]
    ]
  ]);
  let config = {
    stepFwd: x => Belt_MapString.getWithDefault(edges, x, [])
  };
  let state = Fixpoint.make(config, ["R"]);
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B"
  ], "Before: R, A, B in fixpoint");
  assertEqual(Fixpoint.rank(state, "R"), 0, "R has rank 0");
  assertEqual(Fixpoint.rank(state, "A"), 1, "A has rank 1");
  assertEqual(Fixpoint.rank(state, "B"), 2, "B has rank 2");
  let changes = Fixpoint.applyDelta(state, {
    addedToBase: Fixpoint.emptyDelta.addedToBase,
    removedFromBase: Fixpoint.emptyDelta.removedFromBase,
    addedToStep: Fixpoint.emptyDelta.addedToStep,
    removedFromStep: [[
        "R",
        "A"
      ]]
  });
  logArray("Removed elements", changes.removed);
  assertArrayEqual(changes.removed.toSorted(Primitive_string.compare), [
    "A",
    "B"
  ], "A and B were removed (cycle broken)");
  assertArrayEqual(Fixpoint.current(state), ["R"], "After: only R remains");
}

function testRemoveFromBase() {
  console.log("\n=== Test: Remove from Base ===");
  let edges = Belt_MapString.fromArray([
    [
      "R",
      ["A"]
    ],
    [
      "A",
      ["B"]
    ]
  ]);
  let config = {
    stepFwd: x => Belt_MapString.getWithDefault(edges, x, [])
  };
  let state = Fixpoint.make(config, ["R"]);
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B"
  ], "Before: R, A, B in fixpoint");
  let changes = Fixpoint.applyDelta(state, {
    addedToBase: Fixpoint.emptyDelta.addedToBase,
    removedFromBase: ["R"],
    addedToStep: Fixpoint.emptyDelta.addedToStep,
    removedFromStep: Fixpoint.emptyDelta.removedFromStep
  });
  logArray("Removed elements", changes.removed);
  assertArrayEqual(changes.removed.toSorted(Primitive_string.compare), [
    "A",
    "B",
    "R"
  ], "All elements removed when root is removed");
  assertArrayEqual(Fixpoint.current(state), [], "After: empty fixpoint");
}

function testAddToBase() {
  console.log("\n=== Test: Add to Base ===");
  let edges = Belt_MapString.fromArray([
    [
      "R",
      ["A"]
    ],
    [
      "A",
      ["B"]
    ],
    [
      "S",
      ["C"]
    ],
    [
      "C",
      ["D"]
    ]
  ]);
  let config = {
    stepFwd: x => Belt_MapString.getWithDefault(edges, x, [])
  };
  let state = Fixpoint.make(config, ["R"]);
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B"
  ], "Before: R, A, B in fixpoint");
  let changes = Fixpoint.applyDelta(state, {
    addedToBase: ["S"],
    removedFromBase: Fixpoint.emptyDelta.removedFromBase,
    addedToStep: Fixpoint.emptyDelta.addedToStep,
    removedFromStep: Fixpoint.emptyDelta.removedFromStep
  });
  logArray("Added elements", changes.added);
  assertArrayEqual(changes.added.toSorted(Primitive_string.compare), [
    "C",
    "D",
    "S"
  ], "S, C, D added");
  assertArrayEqual(Fixpoint.current(state).toSorted(Primitive_string.compare), [
    "A",
    "B",
    "C",
    "D",
    "R",
    "S"
  ], "After: R, A, B, S, C, D in fixpoint");
}

function testDiamond() {
  console.log("\n=== Test: Diamond (Multiple Paths) ===");
  let edges = Belt_MapString.fromArray([
    [
      "R",
      [
        "A",
        "B"
      ]
    ],
    [
      "A",
      ["C"]
    ],
    [
      "B",
      ["C"]
    ]
  ]);
  let config = {
    stepFwd: x => Belt_MapString.getWithDefault(edges, x, [])
  };
  let state = Fixpoint.make(config, ["R"]);
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B",
    "C"
  ], "Initial: R, A, B, C");
  assertEqual(Fixpoint.rank(state, "C"), 2, "C has rank 2 (shortest path)");
  let changes = Fixpoint.applyDelta(state, {
    addedToBase: Fixpoint.emptyDelta.addedToBase,
    removedFromBase: Fixpoint.emptyDelta.removedFromBase,
    addedToStep: Fixpoint.emptyDelta.addedToStep,
    removedFromStep: [[
        "A",
        "C"
      ]]
  });
  assertArrayEqual(changes.removed, [], "No elements removed (C still reachable via B)");
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B",
    "C"
  ], "After: still R, A, B, C");
  let changes2 = Fixpoint.applyDelta(state, {
    addedToBase: Fixpoint.emptyDelta.addedToBase,
    removedFromBase: Fixpoint.emptyDelta.removedFromBase,
    addedToStep: Fixpoint.emptyDelta.addedToStep,
    removedFromStep: [[
        "B",
        "C"
      ]]
  });
  assertArrayEqual(changes2.removed, ["C"], "C removed (no more paths)");
  assertArrayEqual(Fixpoint.current(state), [
    "R",
    "A",
    "B"
  ], "After: R, A, B");
}

function main() {
  console.log("Fixpoint Algorithm Tests");
  console.log("========================");
  testInitialGraph();
  testExpansion();
  testContraction();
  testCycleContraction();
  testRemoveFromBase();
  testAddToBase();
  testDiamond();
  printSummary();
}

main();

let $$Map;

export {
  $$Map,
  log,
  logArray,
  passed,
  failed,
  failures,
  assertEqual,
  assertArrayEqual,
  printSummary,
  testInitialGraph,
  testExpansion,
  testContraction,
  testCycleContraction,
  testRemoveFromBase,
  testAddToBase,
  testDiamond,
  main,
}
/*  Not a pure module */
