// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as Helpers from "@skipruntime/helpers";
import * as JsonOrderingServiceJs from "./JsonOrderingService.js";

let service = JsonOrderingServiceJs.service;

let defaultOpts = {
  streaming_port: 18091,
  control_port: 18090,
  platform: "wasm",
  no_cors: undefined
};

function start(opts) {
  return SkipruntimeServer.Natural.runService(service, opts);
}

function stop(server) {
  return SkipruntimeServer.Natural.close(server);
}

let Server = {
  service: service,
  defaultOpts: defaultOpts,
  start: start,
  stop: stop
};

let localhost = "127.0.0.1";

function makeBroker(opts) {
  return new Helpers.SkipServiceBroker({
    host: localhost,
    streaming_port: opts.streaming_port,
    control_port: opts.control_port,
    secured: undefined
  }, undefined);
}

let Client = {
  localhost: localhost,
  makeBroker: makeBroker
};

function logKeys(label, entries) {
  let keys = entries.map(param => {
    let k = param[0];
    return [
      JSON.stringify(k),
      typeof k
    ];
  });
  console.log(label, keys);
}

function logKeysWithValues(label, entries) {
  console.log(label);
  entries.forEach(param => {
    let vals = param[1];
    let k = param[0];
    let valStr;
    if (vals.length !== 1) {
      valStr = `[` + vals.map(v => JSON.stringify(v)).join(", ") + `]`;
    } else {
      let v = vals[0];
      valStr = JSON.stringify(v);
    }
    console.log(`  ` + JSON.stringify(k) + ` (` + typeof k + `)`, `=> ` + valStr);
  });
}

async function run() {
  console.log("json-ordering: starting JsonOrderingService on 18090/18091…");
  let server = await start(defaultOpts);
  console.log("json-ordering: service started");
  let broker = makeBroker(defaultOpts);
  let allKeys = await broker.getAll("allKeys", null);
  logKeysWithValues("json-ordering: allKeys initial", allKeys);
  await broker.update("allKeys", [[
      null,
      ["null-top"]
    ]]);
  let allKeysWithNull = await broker.getAll("allKeys", null);
  logKeysWithValues("json-ordering: allKeys with null", allKeysWithNull);
  let slice = await broker.getAll("allKeysSlice", null);
  logKeys("json-ordering: allKeysSlice", slice);
  let take = await broker.getAll("allKeysTake", null);
  logKeys("json-ordering: allKeysTake", take);
  let slices = await broker.getAll("allKeysSlices", null);
  logKeys("json-ordering: allKeysSlices", slices);
  let merged = await broker.getAll("mergedKeys", null);
  logKeys("json-ordering: mergedKeys", merged);
  await SkipruntimeServer.Natural.close(server);
  console.log("json-ordering: service closed");
}

run();

export {
  Server,
  Client,
  logKeys,
  logKeysWithValues,
  run,
}
/* service Not a pure module */
