// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SkipruntimeCore from "../bindings/SkipruntimeCore.res.js";
import * as LiveServiceJs from "./LiveService.js";
import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as Helpers from "@skipruntime/helpers";

let service = LiveServiceJs.service;

function start(opts) {
  return SkipruntimeServer.Natural.runService(service, opts);
}

function stop(server) {
  return SkipruntimeServer.Natural.close(server);
}

let Server = {
  service: service,
  start: start,
  stop: stop
};

let localhost = "127.0.0.1";

function makeBroker(opts) {
  return new Helpers.SkipServiceBroker({
    host: localhost,
    streaming_port: opts.streaming_port,
    control_port: opts.control_port,
    secured: undefined
  }, undefined);
}

async function logSnapshot(broker, label) {
  let snapshot = await broker.getAll("echo", null);
  console.log(label, snapshot);
}

function updateInput(broker, entries) {
  return broker.update("input", entries);
}

async function readOneSse(opts, broker) {
  let uuid = await broker.getStreamUUID("echo", null);
  let streamUrl = `http://` + localhost + `:` + opts.streaming_port.toString() + `/v1/streams/` + uuid;
  console.log("live client: subscribing to", streamUrl);
  let ssePromise = SkipruntimeCore.Context.readFirstSSE(streamUrl);
  await broker.update("input", [[
      "sse",
      ["ping"]
    ]]);
  return await ssePromise;
}

let Client = {
  localhost: localhost,
  makeBroker: makeBroker,
  logSnapshot: logSnapshot,
  updateInput: updateInput,
  readOneSse: readOneSse
};

async function run() {
  let opts = {
    streaming_port: 18081,
    control_port: 18080,
    platform: "wasm",
    no_cors: undefined
  };
  console.log("server: starting wasm service on ports 18080/18081…");
  let server = await start(opts);
  console.log("server: service started");
  let broker = makeBroker(opts);
  await logSnapshot(broker, "live client: initial getAll");
  await broker.update("input", [
    [
      "foo",
      ["baz"]
    ],
    [
      "bar",
      ["qux"]
    ]
  ]);
  await logSnapshot(broker, "live client: after update getAll");
  let sseChunk = await readOneSse(opts, broker);
  console.log("live client: SSE chunk", sseChunk);
  await SkipruntimeServer.Natural.close(server);
  console.log("server: service closed");
}

run();

export {
  Server,
  Client,
  run,
}
/* service Not a pure module */
