// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as Helpers from "@skipruntime/helpers";
import * as LiveHarnessServiceJs from "./LiveHarnessService.js";

let service = LiveHarnessServiceJs.service;

function resetRunStats(prim) {
  LiveHarnessServiceJs.resetRunStats();
}

function getRunStats(prim) {
  return LiveHarnessServiceJs.getRunStats();
}

let defaultOpts = {
  streaming_port: 18081,
  control_port: 18080,
  platform: "wasm",
  no_cors: undefined
};

function start(opts) {
  return SkipruntimeServer.Natural.runService(service, opts);
}

function stop(server) {
  return SkipruntimeServer.Natural.close(server);
}

let Server = {
  service: service,
  resetRunStats: resetRunStats,
  getRunStats: getRunStats,
  defaultOpts: defaultOpts,
  start: start,
  stop: stop
};

let localhost = "127.0.0.1";

function makeBroker(opts) {
  return new Helpers.SkipServiceBroker({
    host: localhost,
    streaming_port: opts.streaming_port,
    control_port: opts.control_port,
    secured: undefined
  }, undefined);
}

async function snapshot(broker, resource, label) {
  let snapshot$1 = await broker.getAll(resource, null);
  console.log(label, snapshot$1);
}

function updateInput(broker, entries) {
  return broker.update("numbers", entries);
}

let Client = {
  localhost: localhost,
  makeBroker: makeBroker,
  snapshot: snapshot,
  updateInput: updateInput
};

let state = {
  total: 0,
  numbers: {}
};

function init() {
  let initialNumbers = [
    [
      "a",
      1
    ],
    [
      "b",
      2
    ],
    [
      "c",
      3
    ],
    [
      "d",
      4
    ],
    [
      "e",
      5
    ],
    [
      "f",
      6
    ],
    [
      "g",
      7
    ],
    [
      "h",
      8
    ],
    [
      "i",
      9
    ],
    [
      "j",
      10
    ]
  ];
  let numbers = Object.fromEntries(initialNumbers);
  let total = Stdlib_Array.reduce(initialNumbers, 0, (acc, param) => acc + param[1]);
  state.total = total;
  state.numbers = numbers;
}

function applyUpdate(key, newValue) {
  let oldValue = Stdlib_Option.getOr(state.numbers[key], 0);
  state.total = state.total - oldValue + newValue;
  state.numbers[key] = newValue;
}

let ClientSum = {
  state: state,
  init: init,
  applyUpdate: applyUpdate
};

async function run() {
  console.log("harness: starting LiveService (wasm) on 18080/18081…");
  let server = await start(defaultOpts);
  console.log("harness: service started");
  let broker = makeBroker(defaultOpts);
  init();
  console.log("harness: client sum (initial)", state.total);
  LiveHarnessServiceJs.resetRunStats();
  await snapshot(broker, "numbers", "harness: numbers");
  await snapshot(broker, "doubled", "harness: doubled");
  await snapshot(broker, "sum", "harness: sum");
  console.log("harness: counters after initial snapshot", LiveHarnessServiceJs.getRunStats());
  await broker.update("numbers", [[
      "c",
      [5]
    ]]);
  await snapshot(broker, "numbers", "harness: numbers after c→5");
  await snapshot(broker, "doubled", "harness: doubled after c→5");
  await snapshot(broker, "sum", "harness: sum after c→5");
  applyUpdate("c", 5);
  console.log("harness: client sum after c→5", state.total);
  console.log("harness: counters after c→5", LiveHarnessServiceJs.getRunStats());
  await SkipruntimeServer.Natural.close(server);
  console.log("harness: service closed");
}

run();

export {
  Server,
  Client,
  ClientSum,
  run,
}
/* service Not a pure module */
