// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LiveServiceMjs from "./LiveService.mjs";
import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let service = LiveServiceMjs.service;

async function run() {
  console.log("live test: starting wasm service on ephemeral ports…");
  try {
    let server = await SkipruntimeServer.Natural.runService(service, {
      streaming_port: 0,
      control_port: 0,
      platform: "wasm",
      no_cors: undefined
    });
    console.log("live test: service started");
    await SkipruntimeServer.Natural.close(server);
    console.log("live test: service closed");
    return;
  } catch (raw_err) {
    let err = Primitive_exceptions.internalToException(raw_err);
    console.error("live test: failed to start service (check for port permissions)", err);
    return;
  }
}

run();

export {
  service,
  run,
}
/* service Not a pure module */
