// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LiveServiceMjs from "./LiveService.mjs";
import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as Helpers from "@skipruntime/helpers";
import * as SkipruntimeCoreHelpersMjs from "../bindings/SkipruntimeCoreHelpers.mjs";

let service = LiveServiceMjs.service;

function readFirstSSE(prim) {
  return SkipruntimeCoreHelpersMjs.readFirstSSE(prim);
}

let localhost = "127.0.0.1";

async function run() {
  console.log("live client: starting wasm service on ports 18080/18081…");
  let server = await SkipruntimeServer.Natural.runService(service, {
    streaming_port: 18081,
    control_port: 18080,
    platform: "wasm",
    no_cors: undefined
  });
  console.log("live client: service started");
  let broker = new Helpers.SkipServiceBroker({
    host: localhost,
    streaming_port: 18081,
    control_port: 18080,
    secured: undefined
  }, undefined);
  let before = await broker.getAll("echo", null);
  console.log("live client: initial getAll", before);
  await broker.update("input", [
    [
      "foo",
      ["baz"]
    ],
    [
      "bar",
      ["qux"]
    ]
  ]);
  let after = await broker.getAll("echo", null);
  console.log("live client: after update getAll", after);
  let uuid = await broker.getStreamUUID("echo", null);
  let streamUrl = `http://` + localhost + `:` + (18081).toString() + `/v1/streams/` + uuid;
  console.log("live client: subscribing to", streamUrl);
  let ssePromise = SkipruntimeCoreHelpersMjs.readFirstSSE(streamUrl);
  await broker.update("input", [[
      "sse",
      ["ping"]
    ]]);
  let sseChunk = await ssePromise;
  console.log("live client: SSE chunk", sseChunk);
  await SkipruntimeServer.Natural.close(server);
  console.log("live client: service closed");
}

run();

export {
  service,
  readFirstSSE,
  localhost,
  run,
}
/* service Not a pure module */
