// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as SkipruntimeCore from "../bindings/SkipruntimeCore.res.js";
import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as Helpers from "@skipruntime/helpers";
import * as LiveHarnessServiceJs from "./LiveHarnessService.js";

let service = LiveHarnessServiceJs.service;

function resetRunStats(prim) {
  LiveHarnessServiceJs.resetRunStats();
}

function getRunStats(prim) {
  return LiveHarnessServiceJs.getRunStats();
}

let defaultOpts = {
  streaming_port: 18081,
  control_port: 18080,
  platform: "wasm",
  no_cors: undefined
};

function start(opts) {
  return SkipruntimeServer.Natural.runService(service, opts);
}

function stop(server) {
  return SkipruntimeServer.Natural.close(server);
}

let Server = {
  service: service,
  resetRunStats: resetRunStats,
  getRunStats: getRunStats,
  defaultOpts: defaultOpts,
  start: start,
  stop: stop
};

let localhost = "127.0.0.1";

function makeBroker(opts) {
  return new Helpers.SkipServiceBroker({
    host: localhost,
    streaming_port: opts.streaming_port,
    control_port: opts.control_port,
    secured: undefined
  }, undefined);
}

async function snapshot(broker, resource, label) {
  let snapshot$1 = await broker.getAll(resource, null);
  console.log(label, snapshot$1);
}

function updateInput(broker, entries) {
  return broker.update("numbers", entries);
}

async function getStreamUrl(opts, broker, resource) {
  let uuid = await broker.getStreamUUID(resource, null);
  return `http://` + localhost + `:` + opts.streaming_port.toString() + `/v1/streams/` + uuid;
}

let Client = {
  localhost: localhost,
  makeBroker: makeBroker,
  snapshot: snapshot,
  updateInput: updateInput,
  getStreamUrl: getStreamUrl
};

let state = {
  total: 0,
  numbers: {},
  subscription: undefined
};

function applyUpdate(key, newValue) {
  let oldValue = Stdlib_Option.getOr(state.numbers[key], 0);
  state.total = state.total - oldValue + newValue;
  state.numbers[key] = newValue;
}

function handleSSEData(data) {
  if (!Array.isArray(data)) {
    return;
  }
  data.forEach(entry => {
    if (!Array.isArray(entry)) {
      return;
    }
    if (entry.length !== 2) {
      return;
    }
    let key = entry[0];
    if (typeof key !== "string") {
      return;
    }
    let values = entry[1];
    if (!Array.isArray(values)) {
      return;
    }
    let match = values[0];
    if (typeof match === "number") {
      return applyUpdate(key, match);
    }
  });
}

function subscribe(streamUrl) {
  let sub = SkipruntimeCore.subscribeSSE(streamUrl, handleSSEData);
  state.subscription = sub;
}

function close() {
  let sub = state.subscription;
  if (sub !== undefined) {
    sub.close();
    state.subscription = undefined;
    return;
  }
}

function getTotal() {
  return state.total;
}

let ClientSum = {
  state: state,
  applyUpdate: applyUpdate,
  handleSSEData: handleSSEData,
  subscribe: subscribe,
  close: close,
  getTotal: getTotal
};

function delay(ms) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => resolve(), ms);
  });
}

async function run() {
  console.log("harness: starting LiveService (wasm) on 18080/18081…");
  let server = await start(defaultOpts);
  console.log("harness: service started");
  let broker = makeBroker(defaultOpts);
  let streamUrl = await getStreamUrl(defaultOpts, broker, "numbers");
  console.log("harness: subscribing to SSE stream", streamUrl);
  subscribe(streamUrl);
  await delay(100);
  console.log("harness: client sum (from SSE)", state.total);
  LiveHarnessServiceJs.resetRunStats();
  await snapshot(broker, "numbers", "harness: numbers");
  await snapshot(broker, "doubled", "harness: doubled");
  await snapshot(broker, "sum", "harness: sum");
  console.log("harness: counters after initial snapshot", LiveHarnessServiceJs.getRunStats());
  await broker.update("numbers", [[
      "c",
      [5]
    ]]);
  await snapshot(broker, "numbers", "harness: numbers after c→5");
  await snapshot(broker, "doubled", "harness: doubled after c→5");
  await snapshot(broker, "sum", "harness: sum after c→5");
  console.log("harness: client sum after c→5 (from SSE)", state.total);
  console.log("harness: counters after c→5", LiveHarnessServiceJs.getRunStats());
  close();
  await SkipruntimeServer.Natural.close(server);
  console.log("harness: service closed");
}

run();

export {
  Server,
  Client,
  ClientSum,
  delay,
  run,
}
/* service Not a pure module */
