// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SkipruntimeServer from "../bindings/SkipruntimeServer.res.js";
import * as Helpers from "@skipruntime/helpers";
import * as LiveHarnessServiceJs from "./LiveHarnessService.js";

let service = LiveHarnessServiceJs.service;

let defaultOpts = {
  streaming_port: 18081,
  control_port: 18080,
  platform: "wasm",
  no_cors: undefined
};

function start(opts) {
  return SkipruntimeServer.Natural.runService(service, opts);
}

function stop(server) {
  return SkipruntimeServer.Natural.close(server);
}

let Server = {
  service: service,
  defaultOpts: defaultOpts,
  start: start,
  stop: stop
};

let localhost = "127.0.0.1";

function makeBroker(opts) {
  return new Helpers.SkipServiceBroker({
    host: localhost,
    streaming_port: opts.streaming_port,
    control_port: opts.control_port,
    secured: undefined
  }, undefined);
}

async function snapshot(broker, resource, label) {
  let snapshot$1 = await broker.getAll(resource, null);
  console.log(label, snapshot$1);
}

function updateInput(broker, entries) {
  return broker.update("numbers", entries);
}

let Client = {
  localhost: localhost,
  makeBroker: makeBroker,
  snapshot: snapshot,
  updateInput: updateInput
};

async function run() {
  console.log("harness: starting LiveService (wasm) on 18080/18081…");
  let server = await start(defaultOpts);
  console.log("harness: service started");
  let broker = makeBroker(defaultOpts);
  await snapshot(broker, "numbers", "harness: initial numbers");
  await snapshot(broker, "doubled", "harness: initial doubled");
  await snapshot(broker, "sum", "harness: initial sum");
  await broker.update("numbers", [
    [
      "a",
      [10]
    ],
    [
      "c",
      [5]
    ]
  ]);
  await snapshot(broker, "numbers", "harness: numbers after update");
  await snapshot(broker, "doubled", "harness: doubled after update");
  await snapshot(broker, "sum", "harness: sum after update");
  await SkipruntimeServer.Natural.close(server);
  console.log("harness: service closed");
}

run();

export {
  Server,
  Client,
  run,
}
/* service Not a pure module */
