// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SkipruntimeCore from "../bindings/SkipruntimeCore.res.js";

let events = [];

let notifier = SkipruntimeCore.Notifier.make({
  subscribed: () => {
    events.push("subscribed");
  },
  notify: update => {
    update.values.forEach(param => {
      events.push(`notify:` + JSON.stringify(param[0]));
    });
  },
  close: () => {
    events.push("close");
  }
});

let update_values = [[
    "k",
    [null]
  ]];

let update_isInitial = true;

let update = {
  values: update_values,
  watermark: "w0",
  isInitial: update_isInitial
};

let update2_values = [
  [
    "k2",
    [null]
  ],
  [
    "k3",
    ["v3"]
  ],
  [
    "k",
    ["v-updated"]
  ]
];

let update2 = {
  values: update2_values,
  watermark: "w1",
  isInitial: undefined
};

notifier.notify(update);

notifier.notify(update2);

notifier.close();

console.log("notifier events", events);

/* notifier Not a pure module */
