// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Server from "@skipruntime/server";

let defaultOptions = {
  streaming_port: 18081,
  control_port: 18080,
  platform: "wasm",
  no_cors: undefined
};

function platformToJs(p) {
  if (p === "native") {
    return "native";
  } else {
    return "wasm";
  }
}

function runService(service, options) {
  return Server.runService(service, options !== undefined ? options : defaultOptions);
}

function close(prim) {
  return prim.close();
}

let Natural = {
  defaultOptions: defaultOptions,
  platformToJs: platformToJs,
  runService: runService,
  close: close
};

export {
  Natural,
}
/* @skipruntime/server Not a pure module */
