// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Core from "@skipruntime/core";
import * as SkipruntimeCoreHelpersMjs from "./SkipruntimeCoreHelpers.mjs";

function loadStatusFromJsRaw(prim) {
  return SkipruntimeCoreHelpersMjs.loadStatusFromJs(prim);
}

function loadStatusToJsRaw(prim) {
  return SkipruntimeCoreHelpersMjs.loadStatusToJs(prim);
}

function fromJs(jsValue) {
  let match = SkipruntimeCoreHelpersMjs.loadStatusFromJs(jsValue);
  switch (match) {
    case "changed" :
      return "changed";
    case "same" :
      return "same";
    default:
      return "incompatible";
  }
}

function toJs(status) {
  if (status === "changed") {
    return SkipruntimeCoreHelpersMjs.loadStatusToJs("changed");
  } else if (status === "incompatible") {
    return SkipruntimeCoreHelpersMjs.loadStatusToJs("incompatible");
  } else {
    return SkipruntimeCoreHelpersMjs.loadStatusToJs("same");
  }
}

let LoadStatus = {
  loadStatusFromJsRaw: loadStatusFromJsRaw,
  loadStatusToJsRaw: loadStatusToJsRaw,
  fromJs: fromJs,
  toJs: toJs
};

function skipError(msg) {
  return new Core.SkipError(msg);
}

function unknownCollection(msg) {
  return new Core.SkipUnknownCollectionError(msg);
}

function unknownResource(msg) {
  return new Core.SkipUnknownResourceError(msg);
}

function rest(msg) {
  return new Core.SkipRESTError(msg);
}

function fetch(msg) {
  return new Core.SkipFetchError(msg);
}

function className(msg) {
  return new Core.SkipClassNameError(msg);
}

function nonUniqueValue(msg) {
  return new Core.SkipNonUniqueValueError(msg);
}

function resourceInUse(msg) {
  return new Core.SkipResourceInstanceInUseError(msg);
}

let Errors = {
  skipError: skipError,
  unknownCollection: unknownCollection,
  unknownResource: unknownResource,
  rest: rest,
  fetch: fetch,
  className: className,
  nonUniqueValue: nonUniqueValue,
  resourceInUse: resourceInUse
};

let Values = {};

let LazyCollection = {};

let EagerCollection = {};

function make(prim0, prim1) {
  return SkipruntimeCoreHelpersMjs.makeMapperClass(prim0, prim1);
}

let Mapper = {
  make: make
};

function make$1(prim0, prim1, prim2, prim3) {
  return SkipruntimeCoreHelpersMjs.makeReducerClass(prim0, prim1, prim2, prim3);
}

let Reducer = {
  make: make$1
};

function make$2(prim0, prim1) {
  return SkipruntimeCoreHelpersMjs.makeLazyComputeClass(prim0, prim1);
}

let LazyCompute = {
  make: make$2
};

function make$3(prim) {
  return SkipruntimeCoreHelpersMjs.makeNotifier(prim);
}

let Notifier = {
  make: make$3
};

function make$4(prim) {
  return SkipruntimeCoreHelpersMjs.makeChangeManager(prim);
}

let ChangeManager = {
  make: make$4
};

let Context = {};

let ServiceDefinition = {};

let ServiceInstanceFactory = {};

let ServiceInstance = {};

let emptyParams = [];

function paramsOrEmpty(p) {
  if (p !== undefined) {
    return p;
  } else {
    return emptyParams;
  }
}

function make$5(mapEntry) {
  return SkipruntimeCoreHelpersMjs.makeMapperClass("Mapper", mapEntry);
}

let Mapper$1 = {
  make: make$5
};

function make$6(initial, add, remove) {
  return make$1("Reducer", initial, add, remove !== undefined ? remove : (_acc, _value, _params) => {});
}

let Reducer$1 = {
  make: make$6
};

function make$7(compute) {
  return SkipruntimeCoreHelpersMjs.makeLazyComputeClass("LazyCompute", compute);
}

let LazyCompute$1 = {
  make: make$7
};

function getArray(prim0, prim1) {
  return prim0.getArray(prim1);
}

function getUnique(prim0, prim1, prim2, prim3) {
  return prim0.getUnique(prim1, prim2 !== undefined ? Primitive_option.valFromOption(prim2) : undefined, prim3 !== undefined ? Primitive_option.valFromOption(prim3) : undefined);
}

function size(prim) {
  return prim.size();
}

function map(params, collection, mapper) {
  return collection.map(mapper, ...(
    params !== undefined ? params : emptyParams
  ));
}

function reduce(params, collection, reducer) {
  return collection.reduce(reducer, ...(
    params !== undefined ? params : emptyParams
  ));
}

function mapReduce(mapperParams, reducerParams, collection, mapper, reducer) {
  return collection.mapReduce(mapper, mapperParams !== undefined ? mapperParams : emptyParams, reducer, ...(
    reducerParams !== undefined ? reducerParams : emptyParams
  ));
}

function slice(prim0, prim1, prim2) {
  return prim0.slice(prim1, prim2);
}

function slices(prim0, prim1) {
  return prim0.slices(prim1);
}

function take(prim0, prim1) {
  return prim0.take(prim1);
}

function merge(prim0, prim1) {
  return prim0.merge(prim1);
}

let EagerCollection$1 = {
  getArray: getArray,
  getUnique: getUnique,
  size: size,
  map: map,
  reduce: reduce,
  mapReduce: mapReduce,
  slice: slice,
  slices: slices,
  take: take,
  merge: merge
};

function createLazyCollection(params, ctx, compute) {
  return ctx.createLazyCollection(compute, ...(
    params !== undefined ? params : emptyParams
  ));
}

function useExternalResource(prim0, prim1) {
  return prim0.useExternalResource(prim1);
}

function jsonExtract(prim0, prim1, prim2) {
  return prim0.jsonExtract(prim1, prim2);
}

let Context$1 = {
  createLazyCollection: createLazyCollection,
  useExternalResource: useExternalResource,
  jsonExtract: jsonExtract
};

let Natural = {
  LLEagerCollection: undefined,
  LLMapper: undefined,
  LLReducer: undefined,
  LLLazyCompute: undefined,
  LLContext: undefined,
  emptyParams: emptyParams,
  paramsOrEmpty: paramsOrEmpty,
  Mapper: Mapper$1,
  Reducer: Reducer$1,
  LazyCompute: LazyCompute$1,
  EagerCollection: EagerCollection$1,
  Context: Context$1
};

export {
  LoadStatus,
  Errors,
  Values,
  LazyCollection,
  EagerCollection,
  Mapper,
  Reducer,
  LazyCompute,
  Notifier,
  ChangeManager,
  Context,
  ServiceDefinition,
  ServiceInstanceFactory,
  ServiceInstance,
  Natural,
}
/* @skipruntime/core Not a pure module */
